### ISSUE TITLE
remove duplicates from export formats

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-ODD#67]
duplicates are propagated to the export formats (thus being published to Zenodo) without proper ID at the root element. Either this should be fixed or even better those duplicates should be removed from the export completely.

**Comment by riedde** [comment]
Could you give a more concrete hint or example?

**Comment by peterstadler** [comment]
Sure, here is an example:
The letter A040001 is a duplicate, i.e. this "letter" got moved to the documents section with the ID A100245 at some time.
The file with the old ID is still kept in our subversion but it redirects to the new location via `<ref type="duplicate" target="A100245"/>`.

The transformation to tei_all (and all other export formats based on this) are now converting the duplicates to "proper" TEI files, yet without any `@xml:id` on the `<TEI>` element, see https://github.com/Edirom/WeGA-ODD/blob/51a662c4dbe65e9e0fd14f0594c48d9ec6e51c00/xsl/to-tei_all.xsl#L240-L277

This struck me during the eXist workshop at the Edirom Summer School I was giving with @martinascholger where we were using the WeGA-data package from Zenodo.

Right now I'm thinking of removing those duplicates from the export – or can you think of any benefit of keeping them?

**Comment by riedde** [comment]
No, I also think that this is a way to resove that issue. The duplicates are neccessary for internal reasons (forwarding). Or might this also be important for the export? Should we keep this information, e.g., by adding the "old" fileID to the header? Something like an "alternative (former) identifier".
But independent from that, removing those "pointer-files" from the export is maybe less invasive.

**Comment by peterstadler** [comment]
I fixed this by adjusting the test and export of the source files (in the subversion data repository) by using Ant `<containsregexp/>` like 
```xml
<target name="validate-letters-against-tei_all" depends="init">
    <local name="docType"/>
    <local name="file.set.docType"/>
    <local name="file.set.processed"/>
    <property name="docType" value="letters"/>
    <fileset id="file.set.docType" dir="${docType}">
        <patternset refid="common.file.pattern"/>
        <not>
            <or>
                <!-- exclude duplicates -->
                <containsregexp expression="&lt;ref\s+type=[&quot;&apos;](duplicate|deletion)[&quot;&apos;]\s+target=[&quot;&apos;][^&quot;]+[&quot;&apos;]"/>
                <containsregexp expression="&lt;ref\s+target=[&quot;&apos;][^&quot;]+[&quot;&apos;]\s+type=[&quot;&apos;](duplicate|deletion)[&quot;&apos;]"/>
            </or>
        </not>
    </fileset>
    <fileset id="file.set.processed" dir="${build.dir}/tei_all/${docType}">
        <patternset refid="common.file.pattern"/>
    </fileset>
    <xslt processor="trax" destdir="${build.dir}/tei_all/${docType}" style="${schema.dir}/../../xsl/to-tei_all.xsl" extension=".xml" useImplicitFileset="false">
        <fileset refid="file.set.docType"/>
    </xslt>
    <run-relaxNG schema.file="${tei_all.rng}" file.set="file.set.processed"/>
</target>
```
